modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Kenny Pasley (Spazley), 1.21.1 port contributors"
description='''
Decouples screen, HUD and tooltip scales and supports per-screen scaling rules.
'''

[[mixins]]
config="scalingguis.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.27.0,)"
ordering="AFTER"
side="CLIENT"
